# 프로덕션 환경 설정

# Hibernate 설정 (프로덕션 환경)
spring.jpa.primary.hibernate.ddl-auto=validate
spring.jpa.primary.hibernate.show-sql=false
spring.jpa.primary.hibernate.format-sql=false

spring.jpa.secondary.hibernate.ddl-auto=validate
spring.jpa.secondary.hibernate.show-sql=false
spring.jpa.secondary.hibernate.format-sql=false
