# 개발 환경 설정

# Hibernate 설정 (개발 환경)
spring.jpa.primary.hibernate.ddl-auto=update
spring.jpa.primary.hibernate.show-sql=true
spring.jpa.primary.hibernate.format-sql=true

spring.jpa.secondary.hibernate.ddl-auto=update
spring.jpa.secondary.hibernate.show-sql=true
spring.jpa.secondary.hibernate.format-sql=true
